<a href="https://colab.research.google.com/github/rmounica/assign3/blob/main/ICP3_700747450.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, *salaries):
        total_salary = sum(salaries) + self.salary
        num_employees = len(salaries) + 1  # Add 1 for the current employee
        return total_salary / num_employees


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, hours_worked):
        super().__init__(name, family, salary, department)
        self.hours_worked = hours_worked


employee1 = Employee("Ruchita", "Surakanti", 50000, "HR")
employee2 = Employee("Anusha", "Belli", 60000, "IT")
fulltime_employee = FulltimeEmployee("Vikram", "Kumar", 70000, "Finance", 40)

average_salary_all = employee1.average_salary(employee2.salary)
average_salary_fulltime = fulltime_employee.average_salary()

print(f"Total number of employees: {Employee.employee_count}")
print(f"Average salary of all employees: {average_salary_all}")
print(f"Average salary of full-time employee: {average_salary_fulltime}")


Total number of employees: 3
Average salary of all employees: 55000.0
Average salary of full-time employee: 70000.0


In [5]:
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 (along axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Original array:")
print(random_vector)
print("\nReshaped array:")
print(reshaped_array)

Original array:
[ 2.52368182  8.62754704 14.18475229  0.         12.27848774 12.18988112
  1.35281127  0.          6.91908446  4.0960859  12.21568953  6.28854527
  0.         12.8987857   7.12132097  8.83781131  0.         14.23662152
  7.54803378 15.86854668]

Reshaped array:
[[ 2.52368182  8.62754704 14.18475229  0.         12.27848774]
 [12.18988112  1.35281127  0.          6.91908446  4.0960859 ]
 [12.21568953  6.28854527  0.         12.8987857   7.12132097]
 [ 8.83781131  0.         14.23662152  7.54803378 15.86854668]]
